### ISSUE TITLE
Confusion with more popular waypoints library on npm

### ISSUE THREAD

**Issue by arjunmehta** [anthonyshort/waypoints#3]
Ideally, libraries with the same name shouldn't be much of an issue, but in this case it would be lovely if the [more popular waypoints library](https://github.com/imakewebthings/waypoints) that is in active development would be the one installed through `npm install waypoints`.

I think the [owner of that library](https://github.com/imakewebthings) has reached out to you to see if there could be something to work out by transferring ownership of the npm name to him somehow.

There is an [open issue](https://github.com/imakewebthings/waypoints/issues/339) in that repo dealing with this! Hope you can help.

Thanks!

**Comment by macx** [comment]
:+1:

**Comment by imakewebthings** [comment]
@anthonyshort has kindly taken care of this.
